preset: laravel

disabled:
  - braces_position
  - binary_operator_spaces
  - single_line_empty_body
  - not_operator_with_successor_space
  - new_with_parentheses
  - phpdoc_align
  - concat_space
  - class_attributes_separation
  - ordered_imports

finder:
  exclude:
    - vendor
